 
 myRdata$Smoking.and.alcohol<-revalue(myRdata$Smoking.and.alcohol,c("Y"=1))
 myRdata$Smoking.and.alcohol<-revalue(myRdata$Smoking.and.alcohol,c("N"=0))
 myRdata$Smoking.and.alcohol<-revalue(myRdata$Smoking.and.alcohol,c("Y"=1))
 myRdata$Smoking.and.alcohol<-revalue(myRdata$Smoking.and.alcohol,c("N"=0))
 myRdata$Gender<-revalue(myRdata$Gender,c("Female"=0))
 myRdata$Gender<-revalue(myRdata$Gender,c("Male"=1))
 myRdata$Maratial_status<-revalue(myRdata$Maratial_status,c("Unmarried"=0))
 myRdata$Maratial_status<-revalue(myRdata$Maratial_status,c("Married"=1))
 
 myRdata$Education<-revalue(myRdata$Education,c("HSC"=1))
 myRdata$Education<-revalue(myRdata$Education,c("Graduate"=2))
 myRdata$Education<-revalue(myRdata$Education,c("PostGraduate"=3))
 myRdata$Regularity<-revalue(myRdata$Regularity,c("Monthly"=1))
 myRdata$Regularity<-revalue(myRdata$Regularity,c("Quaterly"=2))
 myRdata$Regularity<-revalue(myRdata$Regularity,c("Half Yearly"=3))
 myRdata$Regularity<-revalue(myRdata$Regularity,c("Yearly"=4))
myRdata$Regularity<-revalue(myRdata$Regularity,c("Lump Sum"=5))
myRdata$Regularity<-revalue(myRdata$Regularity,c("SSS"=6))
myRdata$Po<-revalue(myRdata$Education,c("PostGraduate"=3))
myRdata$Policy1<-revalue(myRdata$Policy1,c("Jeevan Kishore"=1))
myRdata$Policy1<-revalue(myRdata$Policy1,c("Jeevan Anand"=2))
myRdata$Policy1<-revalue(myRdata$Policy1,c("Jeevan Akshay"=3))
myRdata$Policy1<-revalue(myRdata$Policy1,c("Jeevan Tarang"=4)) 
myRdata$Policy1<-revalue(myRdata$Policy1,c("Money Back Plan"=5))
myRdata$Policy1<-revalue(myRdata$Policy1,c("Term Plan"=6))
myRdata$Policy1<-revalue(myRdata$Policy1,c("Endowment Plan"=7))
myRdata$Policy1<-revalue(myRdata$Policy1,c("Jeevan Saral"=8))
myRdata$Policy2<-revalue(myRdata$Policy2,c("Endowment Plan"=1))
myRdata$Policy2<-revalue(myRdata$Policy2,c("Money Back Plan"=2))
myRdata$Policy2<-revalue(myRdata$Policy2,c("None"=3))
hist(myRdata$Income)
hist(myRdata$Age)
myRdata$Income<-cut(myRdata$Income,c(-1,1,500000,1000000,250000,5000000,10000000),labels = c("1","2","3","4","5","6"))
barplot(table(myRdata$Income),ylim=c(0,1000))



